export const ErrorCodes = {
  // Auth
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  // Resource
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Business logic
  INVALID_SCORE: "INVALID_SCORE",
  TOURNAMENT_CLOSED: "TOURNAMENT_CLOSED",
  ALREADY_REGISTERED: "ALREADY_REGISTERED",
  INSUFFICIENT_SCORES: "INSUFFICIENT_SCORES",
  REGISTRATION_CLOSED: "REGISTRATION_CLOSED",
  REGISTRATION_DUPLICATE: "REGISTRATION_DUPLICATE",
  NOT_ELIGIBLE: "NOT_ELIGIBLE",

  // Server
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
